[package]
name = "truck"
version = "0.1.0"
edition = "2021"

[dependencies]
topological-sort = "0.1.0"
crossbeam = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
toml="0.5.8"
clap = "3.0.0-beta.5"


